version: "3"

services: 

  python:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: 1000
        USER_GID: 1000
        VARIANT: 3
        INSTALL_NODE: "true"
        NODE_VERSION: "lts/*"
    image: qtc.qcteq.io/development/python:1.0.0
    environment:
      - NODE_ENV=development
    container_name: python-container

    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
      
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity 